import Link from 'next/link'
import '../globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
    title: 'Iconic Archives',
    description: 'Generated by create next app',
}

export default function RootLayout({
    children,
}: {
    children: React.ReactNode
}) {
    return (
        <html lang="en">
            <body className="max-w-3xl mx-auto py-10">
                <header>
                    <Link
                        href="/"
                        className="text-large font-bold bg-gradient-to-r from-orange-400 via-red-500 to-purple-600 bg-clip-text text-transparent py20"
                    >
                        Iconic Archives
                    </Link>
                </header>
                <main className="py-20">{children}</main>
            </body>
        </html>
    )
}
